application: snippetysnipsnip
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static/fonts/(.*\.eot)
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.eot)
  mime_type: application/vnd.ms-fontobject

- url: /static/fonts/(.*\.otf)
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.otf)
  mime_type: font/opentype

- url: /static/fonts/(.*\.ttf)
  static_files: static/fonts/\1
  upload: static/fonts/(.*\.ttf)
  mime_type: font/truetype


- url: /static/fonts/(.*\.woff)
  static_files: /static/fonts/\1
  upload: /static/fonts/(.*\.woff)
  mime_type: application/x-font-woff

- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
